trigger:
- master

pr:
- master

variables:
  TargetFramework: netcoreapp3.0
  SdkVersion: 3.0.100-preview5-011568

jobs:
- template: /eng/build.yml
  parameters:
    name: Windows
    pool:
      vmImage: vs2017-win2016

- template: /eng/build.yml
  parameters:
    name: Linux
    pool:
      vmImage: ubuntu-16.04

- template: /eng/build.yml
  parameters:
    name: macOS
    pool:
      vmImage: macOS-10.13
