trigger:
- main

pr:
- main

jobs:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    pool:
      vmImage: windows-2019

- template: /eng/build.yml
  parameters:
    agentOs: Linux
    pool:
      vmImage: ubuntu-20.04

- template: /eng/build.yml
  parameters:
    agentOs: macOS
    pool:
      vmImage: macOS-10.15
