trigger:
- main

pr:
- main

# Schedule a twice monthly build to ensure the pipeline isn't marked as inactive.
schedules:
- cron: '0 0 1,15 * *'
  displayName: Twice monthly build
  branches:
    include:
    - main
  always: true

jobs:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    pool:
      vmImage: windows-latest

- template: /eng/build.yml
  parameters:
    agentOs: Linux
    pool:
      vmImage: ubuntu-latest

- template: /eng/build.yml
  parameters:
    agentOs: macOS
    pool:
      vmImage: macOS-latest
