parameters:
  name: ''
  pool: ''
  strategy: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  strategy: ${{ parameters.strategy }}

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: Install .NET Core SDK
    inputs:
      packageType: sdk
      version: $(SdkVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet publish -c Release -r $(RuntimeID) -f $(TargetFramework) -o $(Build.StagingDirectory) --self-contained false
    displayName: Build the tools
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        pathtoPublish: $(Build.StagingDirectory)
        artifactName: jitutils-$(RuntimeID)-$(TargetFramework)
