parameters:
  name: ''
  pool: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: Install .NET Core SDK
    inputs:
      packageType: sdk
      version: $(SdkVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - ${{ if eq(variables['Agent.OS'], 'Windows_NT') }}:
    - script: bootstrap.cmd
      displayName: Build the tools
      env:
      - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
        value: true

  - ${{ if ne(variables['Agent.OS'], 'Windows_NT') }}:
    - script: ./bootstrap.sh
      displayName: Build the tools
      env:
      - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
        value: true

  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        pathtoPublish: $(Build.StagingDirectory)
        artifactName: ${{ format('jitutils-{0}', parameters.name) }}
