parameters:
  agentOs: ''
  pool: ''

jobs:
- job: ${{ parameters.agentOs }}
  pool: ${{ parameters.pool }}

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: Install .NET Core SDK
    inputs:
      packageType: sdk
      version: $(SdkVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - ${{ if eq(parameters.agentOs, 'Windows') }}:
    - script: bootstrap.cmd
      displayName: Build the tools
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  - ${{ if ne(parameters.agentOs, 'Windows') }}:
    - script: ./bootstrap.sh
      displayName: Build the tools
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        pathtoPublish: $(Build.StagingDirectory)
        artifactName: ${{ format('jitutils-{0}', parameters.agentOs) }}
