<Project Sdk="Microsoft.NET.Sdk">
  <!-- Reuse the analyzer's target framework and existing CommandLine dependency. -->
  <Import Project="../../../src/Directory.Build.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>JitAnalyzeRegression.Tests</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../src/jit-analyze/*.cs" Link="Analyzer/%(Filename)%(Extension)" />
    <Compile Include="../../../src/util/util.cs" Link="Analyzer/util.cs" />
  </ItemGroup>
</Project>
