<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Antigen</RootNamespace>
    <UserSecretsId>ab71806a-3bd8-4fb1-b0e2-9450aec41a9f</UserSecretsId>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0 " />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="*.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExecutionEngine\ExecutionEngine.csproj" />
    <ProjectReference Include="..\Trimmer\Trimmer.csproj" />
    <ProjectReference Include="..\Utilities\Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\antigen.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
